### ISSUE TITLE
I think I have found a typo.

### ISSUE THREAD

**Issue by unosrv** [Rust-Book-Collective/rust-api-dev#1]
PART 1 > Useful Things > in the middle of `Sending data between threads`
...
Also, complex types (struts, tuples, enums) built entirely from primitive types are usually Send and Sync too. But these types are not:
...

It should be `structs` instead of `struts`.

Anyway, I sincerely thank you for the great tutorial.

**Comment by sapati** [comment]
Thanks, fixed.
