### ISSUE TITLE
Missing closing parentheses in a code block.

### ISSUE THREAD

**Issue by kuskhan** [Rust-Book-Collective/rust-api-dev#2]
<img width="618" alt="Screenshot 2024-09-23 at 5 46 40 pm" src="https://github.com/user-attachments/assets/e8d637c7-2dda-4284-8fdb-c6befe31c8c2">
 
PART 1 > Application structure > "To use both a config file and environment variables, we use a layered"

**Comment by sapati** [comment]
Thanks, fixed.
