### ISSUE TITLE
More accurate indentation suggestions for beginners

### ISSUE THREAD

**Issue by kuskhan** [Rust-Book-Collective/rust-api-dev#3]
PART 1 > Understand Axum > Routing > in the first code block
---
<img width="642" alt="Screenshot 2024-09-23 at 8 39 00 pm" src="https://github.com/user-attachments/assets/15a4ed9a-fd64-4d44-b84b-d206ccd4d652">

```
src
  api
    handlers
      mod.rs
      hello.rs
    mod.rs
    v1.rs
```

**Comment by sapati** [comment]
Thanks, fixed!
