### ISSUE TITLE
Suggest omitting `state`

### ISSUE THREAD

**Issue by kuskhan** [Rust-Book-Collective/rust-api-dev#4]
I suggest omitting `state` because the definition of state appears later in the tutorial content.

PART 1 > Understand Axum > Routing >
"We also have to include pub mod api in src/lib.rs. Now we can modify the start_tokio method to use our routes:"

<img width="646" alt="Screenshot 2024-09-24 at 9 08 57 am" src="https://github.com/user-attachments/assets/337248c3-7f7a-4f9f-bc62-a9f007e3041d">

↓
```rust
let router = crate::api::configure();

let listener = tokio::net::TcpListener::bind(addr).await?;
axum::serve(listener, router.into_make_service()).await?;
```

**Comment by sapati** [comment]
Thanks, fixed!
